import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import "./globals.scss";
import { MenuContextDataProvider } from "@/services/menu-data";
import { ChatbotDataContextProvider } from "@/services/chatbot-data";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/9a71b0f99c.js" crossOrigin="anonymous" async></script>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans dark`}>
        <Theme accentColor="teal" className="height-100p">
          <MenuContextDataProvider>
            <ChatbotDataContextProvider>
              {children}
            </ChatbotDataContextProvider>
          </MenuContextDataProvider>
        </Theme>
      </body>
    </html>
  );
}
